"use client";

interface AuditOpportunity {
  priority: number;
  title: string;
  problem: string;
  solution: string;
  tools: string[];
  timeSavedPerWeek: string;
  complexity: "Low" | "Medium" | "High";
  estimatedBuildTime: string;
  roi: string;
}

interface AuditReportData {
  businessName: string;
  executiveSummary: string;
  automationScore: number;
  automationScoreLabel: string;
  opportunities: AuditOpportunity[];
  quickWins: string[];
  recommendedStack: {
    automation: string;
    ai: string;
    database: string;
    reason: string;
  };
  nextSteps: string[];
}

interface AuditReportProps {
  report: AuditReportData;
  onReset: () => void;
}

const COMPLEXITY_CLASS: Record<string, string> = {
  Low: "green",
  Medium: "yellow",
  High: "red",
};

const PRIORITY_ICONS = ["🥇", "🥈", "🥉"];

export default function AuditReport({ report, onReset }: AuditReportProps) {
  const handleDownloadPDF = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    const pageW = 210;
    const margin = 20;
    const maxW = pageW - margin * 2;
    let y = 20;

    const addText = (text: string, size: number, bold = false, color = "#1a1a1a") => {
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setTextColor(color);
      const lines = doc.splitTextToSize(text, maxW);
      lines.forEach((line: string) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += size * 0.45;
      });
      y += 2;
    };

    const addDivider = () => {
      doc.setDrawColor(230, 230, 240);
      doc.line(margin, y, pageW - margin, y);
      y += 6;
    };

    // Header
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, 210, 40, "F");
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor("#ffffff");
    doc.text("AI Business Automation Audit", margin, 20);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`${report.businessName}  •  Score: ${report.automationScore}/100 (${report.automationScoreLabel})`, margin, 32);
    y = 52;

    // Executive Summary
    addText("Executive Summary", 14, true, "#1e1b4b");
    addText(report.executiveSummary, 11, false, "#374151");
    y += 4;
    addDivider();

    // Opportunities
    addText("Automation Opportunities", 14, true, "#1e1b4b");
    y += 2;
    report.opportunities.forEach((opp) => {
      if (y > 240) { doc.addPage(); y = 20; }
      addText(`Priority ${opp.priority}: ${opp.title}`, 12, true, "#4f46e5");
      addText(`Problem: ${opp.problem}`, 10, false, "#374151");
      addText(`Solution: ${opp.solution}`, 10, false, "#374151");
      addText(`Tools: ${opp.tools.join(", ")}  |  Time saved: ${opp.timeSavedPerWeek}  |  Complexity: ${opp.complexity}`, 10, false, "#6b7280");
      addText(`ROI: ${opp.roi}`, 10, true, "#059669");
      y += 4;
    });
    addDivider();

    // Quick Wins
    addText("Quick Wins (Do Today — Free)", 14, true, "#1e1b4b");
    report.quickWins.forEach((win, i) => {
      addText(`${i + 1}. ${win}`, 10, false, "#374151");
    });
    y += 4;
    addDivider();

    // Recommended Stack
    addText("Recommended Tech Stack", 14, true, "#1e1b4b");
    addText(`Automation: ${report.recommendedStack.automation}`, 10, false, "#374151");
    addText(`AI: ${report.recommendedStack.ai}`, 10, false, "#374151");
    addText(`Database: ${report.recommendedStack.database}`, 10, false, "#374151");
    addText(report.recommendedStack.reason, 10, false, "#6b7280");
    y += 4;
    addDivider();

    // Next Steps
    addText("Next Steps", 14, true, "#1e1b4b");
    report.nextSteps.forEach((step, i) => {
      addText(`${i + 1}. ${step}`, 10, false, "#374151");
    });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor("#9ca3af");
    doc.text("Generated by AI Business Process Auditor • github.com/mikkh/ai-biz-auditor", margin, 285);

    doc.save(`${report.businessName.replace(/\s+/g, "_")}_Automation_Audit.pdf`);
  };

  return (
    <div className="report-wrapper">
      {/* Report Actions */}
      <div className="report-actions">
        <button className="btn btn-green" onClick={handleDownloadPDF}>
          ⬇ Download PDF Report
        </button>
        <button className="btn btn-secondary" onClick={onReset}>
          ↩ New Audit
        </button>
      </div>

      {/* Hero / Score */}
      <div className="report-hero">
        <div className="report-hero-top">
          <div>
            <div className="report-title">Automation Audit: {report.businessName}</div>
            <div className="report-subtitle">AI-powered analysis • {new Date().toLocaleDateString()}</div>
          </div>
          <div className="score-badge">
            <div className="score-number">{report.automationScore}</div>
            <div className="score-label">Automation Score</div>
            <div className="score-tag">{report.automationScoreLabel} Potential</div>
          </div>
        </div>
        <div className="executive-summary">{report.executiveSummary}</div>
      </div>

      {/* Opportunities */}
      <div>
        <div className="section-title">🎯 Automation Opportunities</div>
        {report.opportunities.map((opp) => (
          <div className="opportunity-card" key={opp.priority} style={{ marginBottom: 16 }}>
            <div className="opp-header">
              <div className={`priority-badge priority-${opp.priority}`}>
                {opp.priority}
              </div>
              <div style={{ flex: 1 }}>
                <div className="opp-title">{PRIORITY_ICONS[opp.priority - 1]} {opp.title}</div>
                <div className="opp-meta">
                  <span className={`meta-tag ${COMPLEXITY_CLASS[opp.complexity]}`}>
                    {opp.complexity} complexity
                  </span>
                  <span className="meta-tag green">⏱ {opp.timeSavedPerWeek}</span>
                  <span className="meta-tag">🛠 {opp.estimatedBuildTime} to build</span>
                </div>
              </div>
            </div>

            <div className="opp-body">
              <div className="opp-field">
                <div className="opp-field-label">The Problem</div>
                <div className="opp-field-value">{opp.problem}</div>
              </div>
              <div className="opp-field">
                <div className="opp-field-label">The Solution</div>
                <div className="opp-field-value">{opp.solution}</div>
              </div>
            </div>

            <div className="opp-field" style={{ marginBottom: 12 }}>
              <div className="opp-field-label">Recommended Tools</div>
              <div className="tools-list">
                {opp.tools.map((tool) => (
                  <span className="tool-tag" key={tool}>{tool}</span>
                ))}
              </div>
            </div>

            <div className="roi-banner">💰 {opp.roi}</div>
          </div>
        ))}
      </div>

      {/* Quick Wins */}
      <div>
        <div className="section-title">⚡ Quick Wins — Do Today, Free</div>
        <div className="quick-wins-card">
          {report.quickWins.map((win, i) => (
            <div className="quick-win-item" key={i}>
              <div className="win-icon">✅</div>
              <div className="win-text">{win}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Recommended Stack */}
      <div>
        <div className="section-title">🏗️ Recommended Tech Stack</div>
        <div className="stack-card">
          <div className="stack-grid">
            <div className="stack-item">
              <div className="stack-item-label">Automation</div>
              <div className="stack-item-value">{report.recommendedStack.automation}</div>
            </div>
            <div className="stack-item">
              <div className="stack-item-label">AI Engine</div>
              <div className="stack-item-value">{report.recommendedStack.ai}</div>
            </div>
            <div className="stack-item">
              <div className="stack-item-label">Database</div>
              <div className="stack-item-value">{report.recommendedStack.database}</div>
            </div>
          </div>
          <div className="stack-reason">{report.recommendedStack.reason}</div>
        </div>
      </div>

      {/* Next Steps */}
      <div>
        <div className="section-title">🚀 Your Next Steps</div>
        <div className="steps-card">
          {report.nextSteps.map((step, i) => (
            <div className="step-item" key={i}>
              <div className="step-num">{i + 1}</div>
              <div className="step-text">{step}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Bottom actions */}
      <div className="report-actions">
        <button className="btn btn-green" onClick={handleDownloadPDF}>
          ⬇ Download PDF Report
        </button>
        <button className="btn btn-secondary" onClick={onReset}>
          ↩ Run Another Audit
        </button>
      </div>
    </div>
  );
}
